packages:
  - packages/*
  - apps/*

catalogs:
  '@genkit-ai/ai':
    '@genkit-ai/ai': ^1.13.0
  genkit:
    genkit: ^1.13.0
  prisma:
    prisma: latest

onlyBuiltDependencies:
  - '@swc/core'
  - canvas
  - esbuild
  - lefthook
  - protobufjs
  - sharp
