import { GcsArtifactService } from "@google/adk";

/**
 * Service to handle persistence of files generated by the AI Agent
 * I'll keep this class for future customizations specific to Agent nodes.
 */
export class AgentNodeArtifactService extends GcsArtifactService {}
