import { defineConfig } from "tsdown";

export default defineConfig({
	entry: {
		index: "src/metadata.ts",
		server: "src/server/index.ts",
		browser: "src/browser/index.ts",
	},
	format: ["esm"],
	dts: true,
	clean: true,
	sourcemap: true,
	treeshake: true,
	external: [
		"@ai-sdk/google",
		"@dnd-kit/core",
		"@dnd-kit/sortable",
		"@dnd-kit/utilities",
		"@gatewai/api-client",
		"@gatewai/core",
		"@gatewai/data-ops",
		"@gatewai/db",
		"@gatewai/graph-engine",
		"@gatewai/media",
		"@gatewai/node-blur",
		"@gatewai/node-crop",
		"@gatewai/node-export",
		"@gatewai/node-import",
		"@gatewai/node-image-compositor",
		"@gatewai/node-image-gen",
		"@gatewai/node-llm",
		"@gatewai/node-modulate",
		"@gatewai/node-note",
		"@gatewai/node-paint",
		"@gatewai/node-preview",
		"@gatewai/node-resize",
		"@gatewai/node-sdk",
		"@gatewai/node-speech-to-text",
		"@gatewai/node-text",
		"@gatewai/node-text-merger",
		"@gatewai/node-text-to-speech",
		"@gatewai/node-video-compositor",
		"@gatewai/node-video-gen",
		"@gatewai/node-video-gen-first-last-frame",
		"@gatewai/react-canvas",
		"@gatewai/react-store",
		"@gatewai/rpc-client",
		"@gatewai/tsconfig",
		"@gatewai/ui-kit",
		"@google-cloud/secret-manager",
		"@google/adk",
		"@google/genai",
		"@hono/node-server",
		"@hono/zod-validator",
		"@hookform/resolvers",
		"@lobehub/icons",
		"@neodrag/react",
		"@openai/agents",
		"@openai/agents-extensions",
		"@pixi/webworker",
		"@radix-ui/react-slider",
		"@reduxjs/toolkit",
		"@remotion/media",
		"@remotion/player",
		"@remotion/web-renderer",
		"@tailwindcss/vite",
		"@xyflow/react",
		"ai",
		"better-auth",
		"bullmq",
		"class-variance-authority",
		"clsx",
		"cmdk",
		"color",
		"data-urls",
		"date-fns",
		"dotenv",
		"file-type",
		"framer-motion",
		"generic-pool",
		"gl",
		"hono",
		"ioredis",
		"json-schema-to-zod",
		"konva",
		"lodash",
		"loglevel",
		"lucide-react",
		"media-chrome",
		"mime-types",
		"motion",
		"music-metadata",
		"nanoid",
		"next-themes",
		"p-limit",
		"pino",
		"pino-http",
		"pixi.js",
		"query-string",
		"quickjs-emscripten",
		"radix-ui",
		"react",
		"react-dnd",
		"react-dnd-html5-backend",
		"react-dnd-touch-backend",
		"react-dom",
		"react-dropzone",
		"react-fast-compare",
		"react-helmet-async",
		"react-hook-form",
		"react-hotkeys-hook",
		"react-icons",
		"react-konva",
		"react-markdown",
		"react-redux",
		"react-router",
		"react-scan",
		"reflect-metadata",
		"remark-gfm",
		"remotion",
		"sonner",
		"tailwind-merge",
		"tailwindcss",
		"tsyringe",
		"use-debounce",
		"use-image",
		"vite-plugin-node-polyfills",
		"wav",
		"webfontloader",
		"zod",
		"zod-to-json-schema",
	],
});
