import { DataType, HandleType, NodeType, type PrismaClient } from "./client";

export async function SEED_createNodeTemplates(prisma: PrismaClient) {
	const nodes = [
		{
			type: NodeType.Agent,
			displayName: "AI Agent",
			description: "A multi-modal AI agent.",
			category: "AI",
			subCategory: "General",
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "System Prompt",
						required: true,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Instructions",
						required: true,
					},
				],
			},
			defaultConfig: { maxTurns: 10, model: "anthropict/claude-opus-4.5" },
		},
		{
			type: NodeType.Text,
			displayName: "Text",
			description: "A basic text node",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Output,
						dataTypes: [DataType.Text],
						label: "Text",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Preview,
			displayName: "Preview",
			description: "Preview your media",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [
							DataType.Video,
							DataType.Image,
							DataType.Text,
							DataType.Audio,
						],
						required: true,
						label: "Input (Text/Image/Audio/Video)",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.File,
			displayName: "Import",
			description: "Upload your media",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Output,
						dataTypes: [DataType.File],
						label: "File",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Export,
			displayName: "Export",
			description: "A UI download / API output node",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [
							DataType.Text,
							DataType.Image,
							DataType.Video,
							DataType.Audio,
							DataType.Mask,
						],
						required: true,
						label: "Input",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Toggle,
			displayName: "Toggle",
			description: "A toggle for True/False data type",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Output,
						dataTypes: [DataType.Boolean],
						label: "Yes/No",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Resize,
			displayName: "Resize",
			description: "Resize media",
			category: "Image",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Paint,
			displayName: "Paint",
			description: "Draw / Fill Mask on Image",
			category: "Image",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						label: "Background Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Mask],
						label: "Mask",
					},
				],
			},
			defaultConfig: {
				width: 1024,
				height: 1024,
				maintainAspect: true,
				backgroundColor: "#000",
			},
		},
		{
			type: NodeType.Blur,
			displayName: "Blur",
			description: "Apply blur to media",
			category: "Image",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Image",
					},
				],
			},
			defaultConfig: { blurAmount: 0 },
		},
		{
			type: NodeType.Modulate,
			displayName: "Modulate",
			description: "Apply Modulate adjustments to a media",
			category: "Image",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
					},
				],
			},
			defaultConfig: { hue: 0, saturation: 1, lightness: 1, brightness: 1 },
		},
		{
			type: NodeType.Crop,
			displayName: "Crop",
			description: "Crop media",
			category: "Image",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
					},
				],
			},
			defaultConfig: {
				leftPercentage: 0,
				topPercentage: 0,
				widthPercentage: 100,
				heightPercentage: 100,
			},
		},
		{
			type: NodeType.Compositor,
			displayName: "Compositor",
			description: "Compose an image using image or text",
			category: "Image",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: true,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Output Image",
					},
				],
			},
			defaultConfig: { width: 1024, height: 1024 },
		},
		{
			type: NodeType.Note,
			displayName: "Sticky Note",
			description: "A sticky note",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: { create: [] },
			defaultConfig: { backgroundColor: "#ffff88", textColor: "#000000" },
		},
		{
			type: NodeType.Number,
			displayName: "Number",
			description: "A number input node",
			category: "Tools",
			subCategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Output,
						dataTypes: [DataType.Number],
						label: "Number",
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.ImageGen,
			displayName: "Multimodal Image",
			description: "Generate images using text prompt and reference image(s)",
			category: "AI",
			subCategory: "Image",
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: true,
						label: "Prompt",
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: false,
						label: "Reference Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Image",
					},
				],
			},
			defaultConfig: { model: "google/gemini-3-pro-image" },
		},
		{
			type: NodeType.LLM,
			displayName: "LLM",
			description: "Run a LLM model",
			category: "AI",
			subCategory: "Text",
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: true,
						label: "Prompt",
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: false,
						label: "System Prompt",
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: false,
						label: "Image",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Text],
						label: "Text",
					},
				],
			},
			defaultConfig: { model: "openai/gpt-5.2", temperature: 0 },
		},
	];

	for (const node of nodes) {
		await prisma.nodeTemplate.create({ data: node });
	}
}
