// src/node-palette/iconMap.ts
import {
	PiChats,
	PiCloudFog,
	PiCropThin,
	PiCube,
	PiDownloadSimple,
	PiEye,
	PiFaceMask,
	PiFileText,
	PiGitBranch,
	PiHash,
	PiMagnifyingGlass,
	PiNote,
	PiPaintBrushFill,
	PiPaintBucket,
	PiResize,
	PiRobotLight,
	PiStack,
	PiTextT,
	PiToggleLeft,
	PiUploadSimple,
} from "react-icons/pi";

export const NODE_ICON_MAP: Record<
	string,
	React.ComponentType<{ className?: string }>
> = {
	Text: PiTextT,
	Preview: PiEye,
	File: PiUploadSimple,
	Export: PiDownloadSimple,
	Toggle: PiToggleLeft,
	Crawler: PiMagnifyingGlass,
	Resize: PiResize,
	Agent: PiRobotLight,
	ThreeD: PiCube,
	Mask: PiFaceMask,
	Paint: PiPaintBrushFill,
	Crop: PiCropThin,
	Blur: PiCloudFog,
	Compositor: PiStack,
	Describer: PiFileText,
	Router: PiGitBranch,
	// Add fallbacks or additional mappings as needed for other NodeTypes
	Note: PiNote,
	Number: PiHash,
	ImageGen: PiPaintBucket,
	LLM: PiChats,
};
