import type { NodeTemplateCreateInput } from "../../generated/client/models/NodeTemplate";
import { DataType, HandleType, NodeType, type PrismaClient } from "../client";

export async function SEED_createNodeTemplates(prisma: PrismaClient) {
	const nodes: NodeTemplateCreateInput[] = [
		{
			type: NodeType.VideoCompositor,
			displayName: "Video Compositor",
			category: "Video",
			description: "Compose videos",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: true,
			variableInputDataTypes: ["Image", "Audio", "Video", "Text"],
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			defaultConfig: {
				width: 1080,
				height: 1080,
				FPS: 24,
				layerUpdates: {},
			},
		},
		// {
		// 	type: NodeType.VideoGenExtend,
		// 	displayName: "Extend Video",
		// 	category: "AI",
		// 	description: "Extends gemini videos up to 148 seconds",
		// 	subcategory: "Video",
		// 	tokenPrice: 0.0,
		// 	variableInputs: false,
		// 	variableOutputs: false,
		// 	isTerminalNode: true,
		// 	isTransient: false,
		// 	templateHandles: {
		// 		create: [
		// 			{
		// 				type: HandleType.Input,
		// 				dataTypes: [DataType.Video],
		// 				label: "Video to extend",
		// 				required: true,
		// 				order: 0,
		// 			},
		// 			{
		// 				type: HandleType.Input,
		// 				dataTypes: [DataType.Text],
		// 				label: "Prompt",
		// 				required: true,
		// 				order: 1,
		// 			},
		// 			{
		// 				type: HandleType.Input,
		// 				dataTypes: [DataType.Text],
		// 				label: "Negative Prompt",
		// 				required: false,
		// 				order: 2,
		// 			},
		// 			{
		// 				type: HandleType.Output,
		// 				dataTypes: [DataType.Video],
		// 				label: "Result",
		// 				order: 0,
		// 			},
		// 		],
		// 	},
		// 	defaultConfig: {
		// 		model: "veo-3.1-generate-preview",
		// 		aspectRatio: "16:9",
		// 		resolution: "720p",
		// 		durationSeconds: "8",
		// 		personGeneration: "allow_all",
		// 	},
		// },
		{
			type: NodeType.VideoGenFirstLastFrame,
			displayName: "First to last frame video",
			category: "AI",
			description: "Generate videos using first and last frame images",
			subcategory: "Video",
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Prompt",
						required: true,
						order: 0,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						label: "First Frame",
						required: true,
						order: 1,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						label: "Last Frame",
						required: true,
						order: 2,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Negative Prompt",
						required: false,
						order: 3,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Video],
						label: "Output",
						order: 0,
					},
				],
			},
			defaultConfig: {
				model: "veo-3.1-generate-preview",
				aspectRatio: "16:9",
				resolution: "720p",
				durationSeconds: "8",
				personGeneration: "allow_adult",
			},
		},
		{
			type: NodeType.VideoGen,
			displayName: "Generate Video",
			category: "AI",
			description: "A video generation node.",
			subcategory: "Video",
			tokenPrice: 0.0,
			variableInputs: true,
			variableInputDataTypes: ["Image"],
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Prompt",
						required: true,
						order: 0,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Negative Prompt",
						required: false,
						order: 1,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Video],
						label: "Output",
						order: 0,
					},
				],
			},
			defaultConfig: {
				model: "veo-3.1-generate-preview",
				aspectRatio: "16:9",
				resolution: "720p",
				durationSeconds: "8",
				personGeneration: "allow_all",
			},
		},
		{
			type: NodeType.Text,
			displayName: "Text",
			description: "A text input",
			category: "Inputs",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			showInQuickAccess: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Output,
						dataTypes: [DataType.Text],
						label: "Text",
						order: 0,
					},
				],
			},
			defaultConfig: { content: "" },
		},
		{
			type: NodeType.TextMerger,
			displayName: "Text Merger",
			description: "Merges connected texts.",
			category: "Tools",
			subcategory: null,
			variableInputDataTypes: ["Text"],
			tokenPrice: 0.0,
			variableInputs: true,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			showInQuickAccess: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Text",
						order: 0,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Text 2",
						order: 1,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Text],
						label: "Merged Text",
						order: 0,
					},
				],
			},
			defaultConfig: { join: " " },
		},
		{
			type: NodeType.Preview,
			displayName: "Preview",
			description: "Preview the output of a connected node",
			category: "Outputs",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			showInQuickAccess: true,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [
							DataType.Video,
							DataType.Image,
							DataType.Text,
							DataType.Audio,
						],
						required: true,
						label: "Input",
						order: 0,
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.File,
			displayName: "Import",
			description: "Upload your media files",
			category: "Inputs",
			subcategory: null,
			tokenPrice: 0.0,
			showInQuickAccess: true,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Output,
						dataTypes: [DataType.Audio, DataType.Image, DataType.Video],
						label: "File",
						order: 0,
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Export,
			displayName: "Export",
			subcategory: null,
			description: "An UI download / API output node",
			category: "Outputs",
			tokenPrice: 0.0,
			variableInputs: false,
			showInQuickAccess: true,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [
							DataType.Text,
							DataType.Image,
							DataType.Video,
							DataType.Audio,
						],
						required: true,
						label: "Input",
						order: 0,
					},
				],
			},
		},
		{
			type: NodeType.Resize,
			displayName: "Resize",
			description: "Resize media",
			category: "Image",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: undefined,
		},
		{
			type: NodeType.Paint,
			displayName: "Paint",
			description: "Draw / Fill Mask on an image",
			category: "Image",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						label: "Background Image",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Image",
						order: 0,
						description: "Image output, with mask",
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Mask",
						order: 1,
						description: "Image output, only mask",
					},
				],
			},
			defaultConfig: {
				width: 1024,
				height: 1024,
				maintainAspect: true,
				backgroundColor: "#000",
			},
		},
		{
			type: NodeType.Blur,
			displayName: "Blur",
			description: "Apply blur to an image",
			category: "Image",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: { size: 0 },
		},
		{
			type: NodeType.Modulate,
			displayName: "Modulate",
			description: "Apply Modulate adjustments to an image",
			category: "Image",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: { hue: 0, saturation: 1, lightness: 1, brightness: 1 },
		},
		{
			type: NodeType.Crop,
			displayName: "Crop",
			description: "Crop an image",
			category: "Image",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: true,
						label: "Image",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: {
				leftPercentage: 0,
				topPercentage: 0,
				widthPercentage: 100,
				heightPercentage: 100,
			},
		},
		{
			type: NodeType.Compositor,
			displayName: "Image Compositor",
			description: "Compose an image using images and texts",
			category: "Image",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: true,
			variableInputDataTypes: ["Image", "Text"],
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: true,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						label: "Image",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: { width: 1024, height: 1024, layerUpdates: {} },
		},
		{
			type: NodeType.Note,
			displayName: "Sticky Note",
			description: "A sticky note",
			category: "Tools",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: false,
			isTransient: false,
			templateHandles: { create: [] },
			defaultConfig: { backgroundColor: "#ffff88", textColor: "#000" },
		},
		{
			type: NodeType.ImageGen,
			displayName: "Generate Image",
			description: "Generate images using prompt and reference image(s)",
			category: "AI",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: true,
			variableInputDataTypes: ["Image"],
			variableOutputs: false,
			showInQuickAccess: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: true,
						label: "Prompt",
						order: 0,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: false,
						label: "Reference Image",
						order: 1,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Image],
						label: "Image",
						order: 0,
					},
				],
			},
			defaultConfig: { model: "gemini-3-pro-image-preview" },
		},
		{
			type: NodeType.LLM,
			displayName: "LLM",
			description: "Run a LLM model",
			category: "AI",
			subcategory: null,
			tokenPrice: 0.0,
			variableInputs: true,
			variableInputDataTypes: ["Image"],
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			showInQuickAccess: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: true,
						label: "Prompt",
						order: 0,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: false,
						label: "System Prompt",
						order: 1,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Image],
						required: false,
						label: "Image",
						order: 2,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Text],
						label: "Text",
						order: 0,
					},
				],
			},
			defaultConfig: { model: "gemini-3-flash-preview", temperature: 0 },
		},
		{
			type: NodeType.TextToSpeech,
			displayName: "Text to Speech",
			description: "Create audio using text",
			category: "AI",
			subcategory: "Audio",
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						required: true,
						label: "Prompt",
						order: 0,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Audio],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: {
				model: "gemini-2.5-flash-preview-tts",
				voiceName: "Kore",
				languageCode: "en-US",
			},
		},
		{
			type: NodeType.SpeechToText,
			displayName: "Audio Understanding",
			description: "Create text transcript of or extract context from an audio",
			category: "AI",
			subcategory: "Audio",
			tokenPrice: 0.0,
			variableInputs: false,
			variableOutputs: false,
			isTerminalNode: true,
			isTransient: false,
			templateHandles: {
				create: [
					{
						type: HandleType.Input,
						dataTypes: [DataType.Audio],
						required: true,
						label: "Audio",
						order: 0,
					},
					{
						type: HandleType.Input,
						dataTypes: [DataType.Text],
						label: "Prompt",
						order: 1,
					},
					{
						type: HandleType.Output,
						dataTypes: [DataType.Text],
						label: "Result",
						order: 0,
					},
				],
			},
			defaultConfig: { model: "gemini-2.5-flash" },
		},
	];

	for (const node of nodes) {
		const existing = await prisma.nodeTemplate.findUnique({
			where: { type: node.type },
		});
		if (!existing) {
			await prisma.nodeTemplate.create({
				data: node,
			});
		}
	}
}
